apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
